name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/test.yml'
    branches:
      - main
      - dev
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `models`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/models
          token: ${{ secrets.PAT }}
          path: models
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `data-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/data-systems
          token: ${{ secrets.PAT }}
          path: data-systems
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Debug --logger "trx"
            
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory: ${{ github.event.repository.name }}
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false